require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3.3
  TargetRailsVersion: 4.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'lib/tasks/**/*'
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/academic_commons/desc_metadata.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/presentors/custom_join.rb'

Rails/Output:
  Exclude:
    - 'lib/academic_commons/indexer.rb'
