# List of emails to send report and deposit notifications. Can also set
# "from" field in emails. Emails are available at
# Rails.application.config.emails['KEY'].

dev: &dev
  deposit_notification_bcc:
    - YOUR_UNI@columbia.edu
  indexing_report_recipients:
    - YOUR_UNI@columbia.edu
  mail_deposit_recipients:
    - YOUR_UNI@columbia.edu
  mail_deliverer: YOUR_UNI@columbia.edu

development: *dev
test: *dev
academiccommons_dev: *dev
academiccommons_test: *dev
academiccommons_prod: *dev
passenger_prod: *dev
