# Copy this file to config/fedora.yml

development:
  riurl: http://localhost:8983/fedora
  riquery: "select $member from <#ri> where walk ($obj <http://purl.oclc.org/NET/CUL/memberOf> <fedora:%s> and $member <http://purl.oclc.org/NET/CUL/memberOf> $obj) and $member <rdf:type> <http://purl.oclc.org/NET/CUL/Aggregator>"
  rilimit: 100
  user: fedoraAdmin
  password: fedoraAdmin
test:
  riurl: http://localhost:8983/fedora
  riquery: "select $member from <#ri> where walk ($obj <http://purl.oclc.org/NET/CUL/memberOf> <fedora:%s> and $member <http://purl.oclc.org/NET/CUL/memberOf> $obj) and $member <rdf:type> <http://purl.oclc.org/NET/CUL/Aggregator>"
  user: fedoraAdmin
  password: fedoraAdmin

