# Copy this file to config/fedora.yml

development:
  url: http://localhost:8983/fedora
  user: fedoraAdmin
  password: fedoraAdmin
test:
  url: http://localhost:8983/fedora
  user: fedoraAdmin
  password: fedoraAdmin
