# Credentials for google analytics.
# *** DO NOT COMMIT PRODUCTION CREDENTIALS ***

default: &default
  username: USERNAME
  password: PASSWORD
  id: blah

development: *default
test: *default
academiccommons_dev: *default
academiccommons_test: *default
academiccommons_prod: *default
