# Template for secrets.yml. Use this as a base for your local secrets.yml file.
#
# DO NOT COMMIT SECRETS.YML
#
# :cron_errors Email to direct cron errors
# :index_api_key Stores token for metadata editor to authenticate to AC.
# :secret_key_base Your secret key is used for verifying the integrity of signed cookies.
# :ga Google Analytics credentials
#   :user
#   :password
# :okcomputer OkComputer credentials (health check)
#   :user
#   :password
# :sword SWORD credentials
#   :url
#   :collection_slug
#   :user
#   :password

development:
  cron_errors: example@library.columbia.edu
  index_api_key: api_key_for_metadata_editor_app
  secret_key_base: SOMETHINGSOMETHINGSOMETHING
  ga:
    user: google_analytics_user
    password: google_analytics_password
  okcomputer:
    user: monitis
    password: monitis_pass
  sword:
    url: http://example.com/sword
    collection_slug: academic_commons
    user: sword_user
    password: sword_password

test:
  cron_errors: example@library.columbia.edu
  index_api_key: api_key_for_metadata_editor_app
  secret_key_base: SOMETHINGSOMETHINGSOMETHING
  ga:
    user: google_analytics_user
    password: google_analytics_password
  okcomputer:
    user: monitis
    password: monitis_pass
  sword:
    url: http://example.com/sword
    collection_slug: academic_commons
    user: sword_user
    password: sword_password
