# Template for secrets.yml. Use this as a base for your local secrets.yml file.
#
# DO NOT COMMIT SECRETS.YML
#
# :index_api_key Stores token for metadata editor to authenticate to AC.

development:
  index_api_key: api_key_for_metadata_editor_app

test:
  index_api_key: api_key_for_metadata_editor_app
