# Template for secrets.yml. Use this as a base for your local secrets.yml file.
#
# DO NOT COMMIT SECRETS.YML
#
# :index_api_key Stores token for metadata editor to authenticate to AC.
# :ga_username Google Analytics username
# :ga_password Google Analytics password

development:
  index_api_key: api_key_for_metadata_editor_app
  ga_username: google_analytics_user
  ga_password: google_analytics_password

test:
  index_api_key: api_key_for_metadata_editor_app
  ga_username: google_analytics_user
  ga_password: google_analytics_password
