# Template for secrets.yml. Use this as a base for your local secrets.yml file.
#
# DO NOT COMMIT SECRETS.YML
#
# :index_api_key Stores token for metadata editor to authenticate to AC.
# :ga Google Analytics credentials
#   :user
#   :password
# :okcomputer OkComputer credentials (health check)
#   :user
#   :password

development:
  cron_errors: example@library.columbia.edu
  index_api_key: api_key_for_metadata_editor_app
  ga:
    user: google_analytics_user
    password: google_analytics_password
  okcomputer:
    user: monitis
    password: monitis_pass

test:
  index_api_key: api_key_for_metadata_editor_app
  ga:
    user: google_analytics_user
    password: google_analytics_password
  okcomputer:
    user: monitis
    password: monitis_pass
