# Template for solr.yml. Use this as a base for your local solr.yml file.
#
# DO NOT COMMIT SOLR.YML
#

development:
  url: http://127.0.0.1:9983/solr/development

test:
  url: http://127.0.0.1:9983/solr/test
